### ISSUE TITLE
Encoding issue with the included AngularJS files

### ISSUE THREAD

**Issue by tamakisquare** [linemanjs/lineman-angular-template#18]
Not a showstopper but thought I should mention it. 

There seems to be some encoding problem with the included AngularJS files under the `vendor/js/` directory. I see there are dashes, found in docstring, show up as `â€“` when comparing the files to their counterparts downloaded directly from AngularJS's site.

**Comment by 0x11-dev** [comment]
You can just set the correct charset in webserver ,aka nginx or apache and  so on.
