### ISSUE TITLE
ui.bootstrap Datepicker issue

### ISSUE THREAD

**Issue by Egzaell** [linemanjs/lineman-angular-template#61]
After adding datepicker console shows error : 

TypeError: Cannot read property 'join' of undefined

how to fix this?

**Comment by searls** [comment]
Sorry @Egzaell, but we don't provide active development support for projects generated with this template project. I think a better venue for troubleshooting this issue (since it's probably not related to Lineman) would be on StackOverflow as a question about angular & bootstrap
